version: "3.9"
services:
  postgresql:
    image: postgres:${POSTGRES_VERSION}
    container_name: postgres
    restart: unless-stopped
    env_file:
      - ../env/postgres.env
    ports:
      - "5432:5432"
    volumes:
      - ../data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 20
    networks:
      - ms-net

networks:
  ms-net:
    external: true
